#!/usr/bin/env python

from gradelib import *

r = Runner()

@test(10, "thread package with public testcase part1-0")
def test_thread_0():
    r.run_qemu(shell_script([
        'mp1-part1-0',
    ]))
    r.match(
    'mp1-part1-0',
    'thread 1: 100',
	'thread 2: 0',
	'thread 3: 10000',
	'thread 1: 101',
	'thread 2: 1',
	'thread 3: 10001',
	'thread 1: 102',
	'thread 2: 2',
	'thread 3: 10002',
	'thread 1: 103',
	'thread 2: 3',
	'thread 3: 10003',
	'thread 1: 104',
	'thread 2: 4',
	'thread 3: 10004',
	'thread 1: 105',
	'thread 2: 5',
	'thread 1: 106',
	'thread 2: 6',
	'thread 1: 107',
	'thread 2: 7',
	'thread 1: 108',
	'thread 2: 8',
	'thread 1: 109',
	'thread 2: 9',
	'',
	'exited'
    )

@test(10, "thread package with public testcase part1-1")
def test_thread_0():
    r.run_qemu(shell_script([
        'mp1-part1-1',
    ]))
    r.match(
    'mp1-part1-1',
    'thread 1: 100',
	'thread 2: 0',
	'thread 3: 10000',
	'thread 1: 101',
	'thread 2: 1',
	'thread 4: 1000',
	'thread 5: 10',
	'thread 3: 10001',
	'thread 1: 102',
	'thread 2: 2',
	'thread 4: 1001',
	'thread 5: 11',
	'thread 3: 10002',
	'thread 1: 103',
	'thread 2: 3',
	'thread 4: 1002',
	'thread 5: 12',
	'thread 1: 104',
	'thread 2: 4',
	'thread 4: 1003',
	'thread 5: 13',
	'thread 2: 5',
	'thread 4: 1004',
	'thread 5: 14',
	'thread 2: 6',
	'thread 4: 1005',
	'thread 5: 15',
	'thread 2: 7',
	'thread 4: 1006',
	'thread 5: 16',
	'thread 2: 8',
	'thread 4: 1007',
	'thread 4: 1008',
	'',
	'exited'
    )

@test(5, "thread package with public testcase part2-0")
def test_thread_0():
    r.run_qemu(shell_script([
        'mp1-part2-0',
    ]))
    r.match(
	'mp1-part2-0',
	'thread 1: 100',
	'task 2: 101',
	'thread 2: 0',
	'thread 1: 101',
	'thread 2: 1',
	'thread 1: 102',
	'task 2: 103',
	'thread 1: 103',
	'thread 2: 2',
	'thread 1: 104',
	'task 2: 105',
	'thread 2: 3',
	'thread 1: 105',
	'thread 2: 4',
	'',
	'exited'
    )

@test(5, "thread package with public testcase part2-1")
def test_thread_0():
    r.run_qemu(shell_script([
        'mp1-part2-1',
    ]))
    r.match(
	'mp1-part2-1',
	'thread 1: 100',
	'thread 2: 0',
	'task 3: 0',
	'thread 1: 101',
	'thread 2: 1',
	'task 3: 1',
	'thread 1: 102',
	'thread 2: 2',
	'task 3: 2',
	'thread 1: 103',
	'thread 2: 3',
	'task 3: 3',
	'thread 1: 104',
	'thread 2: 4',
	'task 3: 4',
	'thread 1: 105',
	'task 3: 5',
	'thread 1: 106',
	'task 3: 6',
	'thread 1: 107',
	'task 3: 7',
	'thread 1: 108',
	'task 3: 8',
	'thread 1: 109',
	'task 3: 9',
	'thread 3: 10000',
	'thread 3: 10001',
	'thread 3: 10002',
	'thread 3: 10003',
	'thread 3: 10004',
	'',
	'exited'
    )

@test(5, "thread package with public testcase part2-2")
def test_thread_0():
    r.run_qemu(shell_script([
        'mp1-part2-2',
    ]))
    r.match(
	'mp1-part2-2',
	'thread 1: 0',
	'task 1: 1',
	'task 1: 2',
	'task 1: 3',
	'task 1: 4',
	'task 1: 5',
	'task 1: 6',
	'task 1: 7',
	'task 1: 8',
	'task 1: 9',
	'',
	'exited'
    )

run_tests()
